services:
  liderpollo-app:
    image: dvconsultores/sap_hana_lp:latest
    container_name: sap_hana_lp
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env   
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/ppp
      - /dev/net/tun
    volumes:
      - ./vpn/ipsec.conf:/etc/ipsec.conf
      - ./vpn/ipsec.secrets:/etc/ipsec.secrets
      - ./vpn/xl2tpd.conf:/etc/xl2tpd/xl2tpd.conf
      - ./vpn/options.l2tpd.client:/etc/ppp/options.l2tpd.client
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: [ "/bin/sh", "-c", "supervisord -c /etc/supervisor/conf.d/supervisord.conf" ]
    restart: unless-stopped

    
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-lp-sap-hana
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300