version: '3.9'

services:
  mockba:
    image: dvconsultores/sap_hana_lp:latest
    container_name: sap_hana_lp
    env_file:
      - .env
    volumes:
      - .:/app  # Uncomment this line if you need local files
    command: ["python3", "objects.py"]

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-test
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # This allows Watchtower to access Docker
    environment:
      - WATCHTOWER_CLEANUP=true         # Cleanup old images after update
      - WATCHTOWER_POLL_INTERVAL=30     # Check for updates every 30 seconds
      - WATCHTOWER_DEBUG=true            # Optional: Enable debug mode for more logging

networks:
  app-network:
    driver: bridge
