# SQL queries
# Farm Ready
query_farms = """
SELECT WERKS, NAME1
FROM SAPHANADB.T001W
WHERE MANDT = '120' 
AND NAME2 NOT LIKE '%NO USAR%' 
AND NAME1 NOT LIKE '%NO USAR%'
"""

# Warehouse Ready
query_warehouse = """
SELECT LGORT, LGOBE, T001L.WERKS
FROM SAPHANADB.T001L 
INNER JOIN SAPHANADB.T001W ON T001L.WERKS = T001W.WERKS
WHERE T001W.MANDT = '120' 
AND T001L.WERKS >= '4000'
AND T001W.NAME1 NOT LIKE '%NO USAR%' 
AND T001L.LGOBE NOT LIKE '%NO USAR%'
"""

# Purchase Orders in Process
query_purchase_orders = """
SELECT *
FROM SAPHANADB.EKPO
INNER JOIN SAPHANADB.T001L ON EKPO.LGORT = T001L.LGORT
INNER JOIN SAPHANADB.T001W ON EKPO.WERKS = T001W.WERKS
WHERE T001W.NAME1 NOT LIKE '%NO USAR%' AND T001L.LGOBE NOT LIKE '%NO USAR%'
AND EBELN = '4500012723'
-- LIMIT 9000
"""

# Purchase Orders in Process
query_purchase_headers = """
SELECT *
from SAPHANADB.EKKO
WHERE EBELN = '4500012723'
LIMIT 100
"""

# Purchase Orders in Process
query_purchase_orders_history = """
SELECT *
FROM SAPHANADB.EKBE
WHERE EBELN = '4500011936'
LIMIT 100
"""

# Purchase Orders in Process
query_transport = """
SELECT LIFNR, NAME1
FROM SAPHANADB.LFA1
"""