[supervisord]
nodaemon=true

[program:network_manager]
command=/usr/sbin/NetworkManager --no-daemon
autostart=true
autorestart=true
priority=1

[program:vpn_setup]
command=/app/entrypoint.sh
autostart=true
autorestart=false
priority=2
startretries=1

[program:app]
command=python app.py
autostart=true
autorestart=true
priority=3

[program:main]
command=python main.py
autostart=true
autorestart=true
priority=4
