[supervisord]
nodaemon=true


[program:vpn_setup]
command=/app/entrypoint.sh
autostart=true
autorestart=false
priority=1
startretries=1

[program:main]
command=uvicorn main:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true
priority=2

[program:app]
command=python /app/app.py
autostart=true
autorestart=true
priority=3
